version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - git --no-pager diff --exit-code go.mod go.sum

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w
      - -X main.name={{.ProjectName}}
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.url={{.GitURL}}
    main: ./cmd/{{.ProjectName}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

signs:
  - cmd: cosign
    artifacts: checksum
    signature: ${artifact}.sig
    certificate: ${artifact}.pem
    output: true
    args:
      - sign-blob
      - --output-signature=${signature}
      - --output-certificate=${certificate}
      - --oidc-issuer=https://token.actions.githubusercontent.com
      - --oidc-provider=github-actions
      - --yes
      - ${artifact}

changelog:
  use: github-native

release:
  mode: append
  include_meta: true

  footer: |
    ## Verify binary

    ```shell
    cosign verify-blob --verbose \
      --signature "{{.ProjectName}}_{{.Version}}_checksums.txt.sig" \
      --certificate "{{.ProjectName}}_{{.Version}}_checksums.txt.pem" \
      --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
      "{{.ProjectName}}_{{.Version}}_checksums.txt"

    sha256sum --ignore-missing -c "{{.ProjectName}}_{{.Version}}_checksums.txt"
    ```

  # Set this to true if you want to disable just the artifact upload to the SCM.
  # If this is true, GoReleaser will still create the release with the
  # changelog, but won't upload anything to it.
  # skip_upload: true

dockers:
  - image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .Tag }}-amd64"
    dockerfile: Dockerfile
    use: buildx
    goos: linux
    goarch: amd64
    skip_push: false
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.url={{.ReleaseURL}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=org.opencontainers.image.documentation={{.GitURL}}/blob/main/README.md"
      - "--platform=linux/amd64"
  - image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .Tag }}-arm64"
    dockerfile: Dockerfile
    use: buildx
    goos: linux
    goarch: arm64
    skip_push: false
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.url={{.ReleaseURL}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=org.opencontainers.image.documentation={{.GitURL}}/blob/main/README.md"
      - "--platform=linux/arm64"

docker_manifests:
  - name_template: "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .Tag }}"
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .Tag }}-amd64"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:latest"
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .Tag }}-amd64"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .Tag }}-arm64"

docker_signs:
  - cmd: cosign
    artifacts: all
    output: true
    args:
      - sign
      - --oidc-issuer=https://token.actions.githubusercontent.com
      - --oidc-provider=github-actions
      - --yes
      - ${artifact}@${digest}
