name: Retrieve OIDC Token
description: |
  This action retrieves OIDC token's claims from GitHub OpenID Connect Provider.
  Use this action, you can get JWT claims such as `sub`, `workflow` and `job_workflow_ref`.

  ## Usage

  ```yaml
    steps:
      - name: Retrieve OIDC Token
        uses: tmknom/retrieve-oidc-token-action@v0
  ```

outputs:
  payload:
    value: ${{ steps.payload.outputs.json }}
    description: The JWT payload included OIDC token as plain JSON.
  job-workflow-ref:
    value: ${{ steps.parse.outputs.job-workflow-ref }}
    description: The `job_workflow_ref` claim.
  job-workflow-sha:
    value: ${{ steps.parse.outputs.job-workflow-sha }}
    description: The `job_workflow_sha` claim.

runs:
  using: composite

  steps:
    - name: Request ID Token
      id: id-token
      run: |
        token=$(curl --silent --show-error \
          -H "Authorization: Bearer ${ACTIONS_ID_TOKEN_REQUEST_TOKEN}" \
          -H "Accept: application/json; api-version=2.0" \
          -H "Content-Type: application/json" \
          -d "{}" "${ACTIONS_ID_TOKEN_REQUEST_URL}" | \
          jq -r '.value')
        echo "::add-mask::${token}"
        echo "payload=$(cut -d '.' -f 2 <<<"${token}")" >> "${GITHUB_OUTPUT}"
      shell: bash

    - name: Decode payload
      id: payload
      env:
        JWT: ${{ steps.id-token.outputs.payload }}
      run: |
        echo "::group::Decode payload"
        set -x
        base64_encoded="$(tr '_-' '/+' <<<"${JWT}")"
        remainder=$(( ${#base64_encoded} % 4 ))
        if [[ "${remainder}" != 0 ]]; then
          difference=$(( 4 - remainder ))
          padding="$(printf '=%.0s' $(seq 1 "${difference}"))"
          base64_encoded="${base64_encoded}${padding}"
        fi
        decoded="$(base64 -d <<<"${base64_encoded}" | jq -c .)"
        echo "json=${decoded}" >> "${GITHUB_OUTPUT}"
        echo "::endgroup::"
      shell: bash

    - name: Show payload
      env:
        PAYLOAD: ${{ steps.payload.outputs.json }}
      run: |
        echo "::group::Show payload"
        jq . <<<"${PAYLOAD}"
        echo "::endgroup::"
      shell: bash

    - name: Parse
      id: parse
      env:
        PAYLOAD: ${{ steps.payload.outputs.json }}
      run: |
        echo "::group::Show payload"
        set -x
        {
          echo "sub=$(jq -r '.sub' <<<"${PAYLOAD}")"
          echo "iat=$(jq -r '.iat' <<<"${PAYLOAD}")"
          echo "aud=$(jq -r '.aud' <<<"${PAYLOAD}")"
          echo "jti=$(jq -r '.jti' <<<"${PAYLOAD}")"
          echo "job-workflow-ref=$(jq -r '.job_workflow_ref' <<<"${PAYLOAD}")"
          echo "job-workflow-sha=$(jq -r '.job_workflow_sha' <<<"${PAYLOAD}")"
        } >> "${GITHUB_OUTPUT}"
      shell: bash
