name: Internal Test GitHub Actions
on:
  workflow_dispatch:
  pull_request:
    paths: [".github/workflows/github-actions.yml", ".github/workflows/_internal-test-github-actions.yml"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
      pull-requests: write
      id-token: write
      packages: write
    outputs:
      base-branch: ${{ steps.base.outputs.branch }}
      dependabot-branch: ${{ steps.dependabot.outputs.branch }}
    steps:
      - name: Checkout default branch
        uses: tmknom/checkout-action@v1
        with:
          ref: ${{ github.event.repository.default_branch }}

      - name: Git config as Dependabot
        run: |
          set -x
          git config user.name "dependabot[bot]"
          git config user.email "49699333+dependabot[bot]@users.noreply.github.com"

      - name: Create base branch
        id: base
        run: |
          set -x
          branch="pseudo/${GITHUB_JOB}-${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT}"
          echo "branch=${branch}" >> "${GITHUB_OUTPUT}"
          git switch -c "${branch}"
          git push origin "${branch}"

      # TODO Change secrets name
      - name: Private Generate GitHub Token
        id: gha
        uses: tmknom/private-generate-github-token-action@86f118410bc0dfedbb0e4601175cf8a60f21b5d7 # v0.2.0
        with:
          repositories: test-goreleaser # TODO

      - name: Create dependabot branch
        id: dependabot
        env:
          PACKAGE_ECOSYSTEM: github_actions
          COMMIT_MESSAGE_FILE: .github/fixtures/github_actions.txt
          BASE_BRANCH: ${{ steps.base.outputs.branch }}
          GITHUB_TOKEN: ${{ steps.gha.outputs.token }}
        run: |
          set -x
          branch="dependabot/${PACKAGE_ECOSYSTEM}/pseudo/repo/${GITHUB_JOB}${GITHUB_RUN_ID}${GITHUB_RUN_ATTEMPT}-1.2.3"
          echo "branch=${branch}" >> "${GITHUB_OUTPUT}"
          git switch -c "${branch}" "${BASE_BRANCH}"
          git commit -m "$(cat "${COMMIT_MESSAGE_FILE}")" --allow-empty
          git push origin "${branch}"
          gh pr create --base "${BASE_BRANCH}" --head "${branch}" --fill-first

      - name: Revoke GitHub Token
        if: ${{ always() }}
        uses: tmknom/revoke-github-token-action@3ab58f0a8cc1f0911d071e243343bc0a003d0d1b # v0.1.0
        with:
          token: ${{ steps.gha.outputs.token }}

  exercise:
    needs: [setup]
    uses: ./.github/workflows/reusable-merge-github-actions.yml
    with:
      pull-request: ${{ needs.setup.outputs.dependabot-branch }}
      github-actor: ${{ github.repository_owner }}
      update-type: version-update:semver-patch
    permissions:
      contents: write
      pull-requests: write

  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [setup, exercise]
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Verify state
        env:
          DEPENDABOT_BRANCH: ${{ needs.setup.outputs.dependabot-branch }}
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          set -x
          result="$(gh pr view "${DEPENDABOT_BRANCH}" --json state --jq .state)"
          test "${result}" = "MERGED"

  teardown:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [setup, exercise, verify]
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Close pull request
        env:
          DEPENDABOT_BRANCH: ${{ needs.setup.outputs.dependabot-branch }}
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          set -x
          gh pr close "${DEPENDABOT_BRANCH}" || true

      - name: Delete branches
        env:
          BASE_BRANCH: ${{ needs.setup.outputs.base-branch }}
          DEPENDABOT_BRANCH: ${{ needs.setup.outputs.dependabot-branch }}
        run: |
          set -x
          git push origin "${DEPENDABOT_BRANCH}" --delete || true
          git push origin "${BASE_BRANCH}" --delete || true
