name: Jobs encryption
on:
  push:
  workflow_dispatch:

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  prepare:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Generate
        run: |
          set -x
          printenv | grep GITHUB_ | sort -u

      - name: env action
        uses: tmknom/test-goreleaser/.github/actions/env@170a5f659417d98b49d84658f492bf1cdfe03c69
