name: Jobs secrets
on:
  push:

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  prepare:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      secret: ${{ steps.generate.outputs.secret }}
      base64: ${{ steps.generate.outputs.base64 }}
    steps:
      - name: Generate
        id: generate
        run: |
          set -x
          secret="SuperSecrets!"
          echo "::add-mask::${secret}"
          echo "secret=${secret}" >> "${GITHUB_OUTPUT}"
          echo "base64=$(base64 <<<"${secret}")" >> "${GITHUB_OUTPUT}"

  release:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [prepare]
    steps:
      - name: Verify token
        id: decode
        env:
          SECRET: ${{ needs.prepare.outputs.secret }}
          BASE64_SECRET: ${{ needs.prepare.outputs.base64 }}
        run: |
          set -x
          echo "${SECRET}"
          echo "${BASE64_SECRET}"
          wc -c <<<"${SECRET}"
          wc -c <<<"${BASE64_SECRET}"

          if [[ "${BASE64_SECRET}" != "" ]]; then
            base64 -d <<<"${BASE64_TOKEN}"
          fi
