name: Release
on:
  workflow_dispatch:
    inputs:
      bump-level:
        type: choice
        required: true
        description: Bump up to [patch / minor / major]
        options:
          - patch
          - minor
          - major
        default: minor

concurrency: ${{ github.workflow }}

permissions: {}

jobs:
  call:
    uses: tmknom/release-workflows/.github/workflows/go.yml@c3754f02011eb056504b47da35763d9782ae762f # v0.12.5
    # uses: ./.github/workflows/reusable-release.yml
    # uses: tmknom/test-goreleaser/.github/workflows/reusable-release.yml@e61bbb91c60bef62eb146237819a8c48ace314f0 # v0.26.1
    # uses: tmknom/release-workflows/.github/workflows/go.yml@main
    with:
      bump-level: ${{ inputs.bump-level }}
      homebrew-tap-repository: homebrew-test-tap
    permissions:
      contents: write
      packages: write
      id-token: write
      attestations: write
