name: Reusable JWT

on:
  workflow_call:

jobs:
  extract:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Request ID Token
        id: id-token
        uses: ./.github/actions/request-id-token-action/

      - name: Show header
        env:
          HEADER: ${{ steps.id-token.outputs.jwt-header }}
        run: |
          jq . <<<"${HEADER}"

      - name: Show payload
        env:
          PAYLOAD: ${{ steps.id-token.outputs.jwt-payload }}
        run: |
          jq . <<<"${PAYLOAD}"

      - name: Show
        env:
          JOB_WORKFLOW_REF: ${{ steps.id-token.outputs.job-workflow-ref }}
          JOB_WORKFLOW_SHA: ${{ steps.id-token.outputs.job-workflow-sha }}
        run: |
          echo "JOB_WORKFLOW_REF: ${JOB_WORKFLOW_REF}"
          echo "JOB_WORKFLOW_SHA: ${JOB_WORKFLOW_SHA}"

# {
#   "jti": "f04ec113-ffb1-45df-a763-8c0c38533d3f",
#   "sub": "repo:tmknom/test-goreleaser:ref:refs/heads/main",
#   "aud": "https://github.com/tmknom",
#   "ref": "refs/heads/main",
#   "sha": "98ebcecb092d179526cb3200bab311bd1934ed20",
#   "repository": "tmknom/test-goreleaser",
#   "repository_owner": "tmknom",
#   "repository_owner_id": "3865036",
#   "run_id": "12732586816",
#   "run_number": "4",
#   "run_attempt": "1",
#   "repository_visibility": "public",
#   "repository_id": "422815758",
#   "actor_id": "3865036",
#   "actor": "tmknom",
#   "workflow": "job_workflow_ref",
#   "head_ref": "",
#   "base_ref": "",
#   "event_name": "workflow_dispatch",
#   "ref_protected": "false",
#   "ref_type": "branch",
#   "workflow_ref": "tmknom/test-goreleaser/.github/workflows/jwt.yml@refs/heads/main",
#   "workflow_sha": "98ebcecb092d179526cb3200bab311bd1934ed20",
#   "job_workflow_ref": "tmknom/test-goreleaser/.github/workflows/reusable-jwt.yml@2c2d91ecdbb0f3e80354098ee13fba1ec59b4dd4",
#   "job_workflow_sha": "2c2d91ecdbb0f3e80354098ee13fba1ec59b4dd4",
#   "runner_environment": "github-hosted",
#   "iss": "https://token.actions.githubusercontent.com",
#   "nbf": 1736676198,
#   "exp": 1736677098,
#   "iat": 1736676798
# }
