name: Reusable Bump Version
on:
  workflow_call:
    inputs:
      bump-level:
        type: string
        required: true
        description: Determines which part of the version to increment [patch/minor/major]
    secrets:
      app-id:
        required: true
        description: GitHub App ID
      app-private-key:
        required: true
        description: GitHub App private key

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  bump:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/create-github-app-token@5d869da34e18e7287c1daad50e0b8ea0f506ce69 # v1.11.0
        id: github-app
        with:
          app-id: ${{ secrets.app-id }}
          private-key: ${{ secrets.app-private-key }}

      - name: Checkout
        uses: tmknom/checkout-action@v1
        with:
          ref: ${{ github.event.repository.default_branch }}
          token: ${{ steps.github-app.outputs.token }}

      - name: Bump Version
        id: bump
        uses: tmknom/bump-version-action@87bed7f224292cab5b46a4cae9897bbf64153f00 # v0.2.1
        with:
          bump-level: ${{ inputs.bump-level }}

      - name: Push Version Tag
        uses: tmknom/push-version-tag-action@a9d1b46f9c29d3db510771452257b228bfd8a33f # v0.1.1
        with:
          version: ${{ steps.bump.outputs.version }}
