name: Reusable jwt

on:
  workflow_call:

jobs:
  extract-jwt:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Setup OIDC Token
        id: oidc
        env:
          ACTIONS_ID_TOKEN_REQUEST_URL: ${{ secrets.ACTIONS_ID_TOKEN_REQUEST_URL }}
          ACTIONS_ID_TOKEN_REQUEST_TOKEN: ${{ secrets.ACTIONS_ID_TOKEN_REQUEST_TOKEN }}
        run: |
          token=$(curl -s -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL")
          echo "::add-mask::${token}"
          echo "token=${token}" >> "${GITHUB_OUTPUT}"

      - name: Parse
        env:
          OIDC_TOKEN: ${{ steps.oidc.outputs.token }}
        run: |
          set -x
          base64_payload="$(cut -d '.' -f 2 <<<"${OIDC_TOKEN}" | tr -d '\n')"
          payload=$(base64 -d <<<"${base64_payload}" | jq .)
          job_workflow_ref=$(jq -r '.job_workflow_ref' <<<"${payload}")
          echo "job_workflow_ref: ${job_workflow_ref}"
