name: Merge GitHub Actions
on:
  workflow_call:
    inputs:
      pull-request:
        type: string
        required: true
        description: Specifies the pull request to merge as a `number`, `url`, or `branch`.
      patch:
        type: boolean
        default: true
        required: false
        description: Whether to merge the patch version.
      minor:
        type: boolean
        default: true
        required: false
        description: Whether to merge the minor version.
      major:
        type: boolean
        default: false
        required: false
        description: Whether to merge the major version.
      github-actor:
        type: string
        default: dependabot[bot]
        required: false
        description: The name of the person or app that initiated the workflow.
      update-type:
        type: string
        required: false
        description: Update to one or more semantic versioning levels that supports `version-update:semver-patch`, `version-update:semver-minor`, and `version-update:semver-major`.

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  merge:
    if: ${{ github.actor == inputs.github-actor }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Fetch metadata
        if: ${{ inputs.github-actor == 'dependabot[bot]' }}
        id: metadata
        uses: dependabot/fetch-metadata@dbb049abf0d677abbd7f7eee0375145b417fdd34 # v2.2.0

      - name: Validate package ecosystem
        uses: tmknom/validation-action@f654c365b696d6053efe5fb299e8d6ea2bb9f3c8 # v0.3.0
        with:
          enum: github_actions
          value: ${{ steps.metadata.outputs.package-ecosystem || 'github_actions' }}

      - name: Validate Dependabot Mergeable
        id: check
        uses: tmknom/validate-dependabot-mergeable-action@e6938df544c3b522d591205b16d47b3f692c4fff # v0.1.0
        with:
          update-type: ${{ steps.metadata.outputs.update-type || inputs.update-type }}
          patch: ${{ inputs.patch }}
          minor: ${{ inputs.minor }}
          major: ${{ inputs.major }}

      - name: Approve PR
        if: ${{ steps.check.outputs.mergeable == 'true' }}
        uses: tmknom/approve-pr-action@8542c6214a4d7e2c116fe7b4c783918ea79a0e06 # v0.1.0
        with:
          pull-request: ${{ inputs.pull-request }}

      - name: Merge PR
        if: ${{ steps.check.outputs.mergeable == 'true' }}
        uses: tmknom/merge-pr-action@857c5b4c314243e3ca49288468e062b82060078a # v0.3.0
        with:
          pull-request: ${{ inputs.pull-request }}
