name: Merge GitHub Actions
on:
  workflow_call:
    inputs:
      pull-request:
        type: string
        required: true
        description: Specifies the pull request to merge as a `number`, `url`, or `branch`.
      patch:
        type: boolean
        default: true
        required: false
        description: Whether to merge the patch version.
      minor:
        type: boolean
        default: true
        required: false
        description: Whether to merge the minor version.
      major:
        type: boolean
        default: false
        required: false
        description: Whether to merge the major version.
      github-actor:
        type: string
        default: dependabot[bot]
        required: false
        description: The name of the person or app that initiated the workflow.

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  merge:
    if: ${{ github.actor == inputs.github-actor }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Fetch metadata
        id: metadata
        uses: dependabot/fetch-metadata@dbb049abf0d677abbd7f7eee0375145b417fdd34 # v2.2.0

      - name: Validate package ecosystem
        uses: tmknom/validation-action@f654c365b696d6053efe5fb299e8d6ea2bb9f3c8 # v0.3.0
        with:
          enum: github_actions
          value: ${{ steps.metadata.outputs.package-ecosystem }}

      - name: Check mergeable
        id: check
        env:
          PATCH: ${{ inputs.patch }}
          MINOR: ${{ inputs.minor }}
          MAJOR: ${{ inputs.major }}
          UPDATE_TYPE: ${{ steps.metadata.outputs.update-type }}
        run: |
          set -x
          mergeable=false
          if [[ "${UPDATE_TYPE}" == "version-update:semver-patch" && "${PATCH}" == "true" ]]; then
            mergeable=true
          fi
          if [[ "${UPDATE_TYPE}" == "version-update:semver-minor" && "${MINOR}" == "true" ]]; then
            mergeable=true
          fi
          if [[ "${UPDATE_TYPE}" == "version-update:semver-major" && "${MAJOR}" == "true" ]]; then
            mergeable=true
          fi
          echo "mergeable=${mergeable}" >> "${GITHUB_OUTPUT}"

      - name: Approve PR
        if: ${{ steps.check.outputs.mergeable == 'true' }}
        env:
          PULL_REQUEST: ${{ inputs.pull-request }}
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          set -x
          gh pr review "${PULL_REQUEST}" --approve

      - name: Merge PR
        if: ${{ steps.check.outputs.mergeable == 'true' }}
        uses: tmknom/merge-pr-action@b3282fa89f36b6c7898b194b1f7287dd09249d09 # v0.1.0
        with:
          pull-request: ${{ inputs.pull-request }}
