name: Test Approve
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      # TODO Disable 'allow GitHub Actions to create and approve pull requests' setting
      - name: Approve PR
        uses: tmknom/approve-pr-action@feat/add-action
        with:
          pull-request: 10
