name: ZZZ Release
on:
  push:
    tags:
      - v*

concurrency: ${{ github.workflow }}

permissions: {}

jobs:
  call:
    uses: ./.github/workflows/reusable-release.yml
    permissions:
      contents: write
      packages: write
      id-token: write
      attestations: write
